### ISSUE TITLE
Add "soft refresh" button

### ISSUE THREAD

**Issue by jeremyckahn** [iamapunkmonkey/icanteventoday#3]
**ACCEPTANCE CRITERIA**

As a user
When I go to http://icanteven.today/
I want to click a button on the page to get a new quote and GIF
Without hitting my browser's "refresh" button
So that I can save on round-trip bandwidth and get a new quote more quickly

**Comment by jabbowaki** [comment]
:+1: need this plz thanks

**Comment by iamapunkmonkey** [comment]
Implemented with commit 0e21e494b90bd58ebbbadbaa7e5c2f3a4a27f6b6.

User can click on gif or click on Still can't even? link.
